# Generated by Django 5.2.12 on 2026-03-25 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Status',
            new_name='status',
        ),
    ]
